services:
  - type: web
    name: blog-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate
      python create_superuser.py
      python manage.py collectstatic --no-input
      gunicorn blogapp_api.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        value: blog-backend-hpl0.onrender.com
        value: "False"
