services:
  - type: web
    name: blog-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python force_migrations.py
      python create_superuser.py
      python create_test_posts.py
      gunicorn blogapp_api.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: blog-backend-hpl0.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://blog-aftab.netlify.app
      - key: DJANGO_SECRET_KEY
        generateValue: true
    databases:
      - name: blog_db
        databaseName: blog_db
        user: blog_user
    autoDeploy: true
